name: Notes Application CI Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: "17.6.0"
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: "7.0.12"
    - name: Install dependencies
      run: npm install --prefix src
  unit-tests:
   needs: lint
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Use Node.js 17.x
     uses: actions/setup-node@v3
     with:
       node-version: "17.6.0"
   - name: Install dependencies
     run: npm install --prefix src
   - name: Run unit tests
     run: npm run test-unit --prefix src
   - if: success() || failure()
     uses: actions/upload-artifact@v3
     with:
       name: code-coverage-report
       path: /src/coverage/lcov/note.js.html
