name: Notes Application CI Pipeline
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: "17.6.0"
    - name: Install dependencies
      run: npm install --prefix src
    - name: run lint
      run: npm run test-lint --prefix src
